# Generated by Django 3.2.7 on 2021-10-18 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_formation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='formation',
        ),
    ]
