# Generated by Django 3.2.7 on 2021-10-18 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_productimages_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('video', models.FileField(upload_to='')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.formation')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductImages',
        ),
    ]
