# Generated by Django 3.2.7 on 2021-10-18 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20211018_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='durée_formation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='formation',
            name='nombre_cours',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='formation',
            name='prof',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
