# Generated by Django 3.2.7 on 2021-10-18 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20211018_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='product',
        ),
        migrations.DeleteModel(
            name='client',
        ),
        migrations.DeleteModel(
            name='formation',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
