# Generated by Django 3.2.7 on 2021-10-26 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
