# Generated by Django 3.2.7 on 2021-10-29 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20211029_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='prof',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
