# Generated by Django 3.2.7 on 2021-10-29 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_formation_prof'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prof',
        ),
    ]
