# Generated by Django 3.2.7 on 2021-10-29 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_prof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='prof',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
