# Generated by Django 3.2.7 on 2021-10-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_formation_prof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='prof',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='Prof',
        ),
    ]
