# Generated by Django 3.2.7 on 2021-10-29 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_prof_nom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prof',
            name='user',
        ),
    ]
