# Generated by Django 3.2.7 on 2021-11-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_demmande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demmande',
            name='reçu',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
