# Generated by Django 3.2.7 on 2021-11-07 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_auto_20211107_0130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='order',
            name='reçu',
        ),
        migrations.RemoveField(
            model_name='order',
            name='wilaya',
        ),
    ]
