# Generated by Django 3.2.7 on 2021-11-07 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_auto_20211107_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='demmande',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.client'),
        ),
    ]
