# Generated by Django 3.2.7 on 2021-11-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_examen_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='reçu',
            field=models.FileField(blank=True, null=True, upload_to='static/images'),
        ),
    ]
