# Generated by Django 3.2.7 on 2021-11-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_alter_order_reçu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='reçu',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
    ]
