# Generated by Django 3.2.7 on 2021-11-21 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_alter_order_reçu'),
    ]

    operations = [
        migrations.CreateModel(
            name='année',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='reçu',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
