# Generated by Django 3.2.7 on 2021-11-21 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_auto_20211121_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='année',
            name='niveau',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.niveau'),
        ),
    ]
