# Generated by Django 3.2.7 on 2021-11-21 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_année_niveau'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formation',
            name='niveau',
        ),
        migrations.AddField(
            model_name='formation',
            name='année',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.année'),
        ),
    ]
