# Generated by Django 3.2.7 on 2021-11-21 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='prof',
            name='matière',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
