# Generated by Django 3.2.7 on 2021-11-21 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_alter_prof_matière'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prof',
            name='matière',
        ),
    ]
