# Generated by Django 3.2.7 on 2021-11-25 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_remove_prof_matière'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='année',
            name='niveau',
        ),
        migrations.RemoveField(
            model_name='client',
            name='user',
        ),
        migrations.DeleteModel(
            name='contact',
        ),
        migrations.RemoveField(
            model_name='examen',
            name='product',
        ),
        migrations.RemoveField(
            model_name='formation',
            name='année',
        ),
        migrations.RemoveField(
            model_name='formation',
            name='prof',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='video',
            name='product',
        ),
        migrations.DeleteModel(
            name='année',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Examen',
        ),
        migrations.DeleteModel(
            name='Formation',
        ),
        migrations.DeleteModel(
            name='Niveau',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='Prof',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
