# Generated by Django 3.2.7 on 2021-12-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0050_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='série',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
