# Generated by Django 3.2.7 on 2021-12-19 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0051_formation_série'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='série',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
