# Generated by Django 3.2.7 on 2021-12-28 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0054_prof_matière'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Examen',
        ),
    ]
