# Generated by Django 4.0 on 2022-01-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0055_delete_examen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='duré_video',
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.CharField(max_length=255),
        ),
    ]
